version: "3.9"

services:
    # Base de données PostgreSQL
    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: crewai_marketing
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user -d crewai_marketing"]
            interval: 10s
            timeout: 5s
            retries: 5

    # Application FastAPI
    app:
        build: .
        env_file:
            - .env
        environment:
            - DATABASE_URL=postgresql://user:password@postgres:5432/crewai_marketing
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - SERPER_API_KEY=${SERPER_API_KEY}
            - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
            - CREWAI_TELEMETRY=False
        ports:
            - "8000:8000"
        volumes:
            - ./uploads:/app/uploads
            - ./knowledge:/app/knowledge
            - ./src:/app/src
        depends_on:
            postgres:
                condition: service_healthy
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
        tty: true

volumes:
    postgres_data:
